Repository ureca-team-juksoon/juksoon-be, pull requests merged in 2025-05, with the labels that each got.

#2 [Feat] S3 기본 설정 추가
  .github/pull_request_template.md
  build.gradle
  src/main/java/com/ureca/juksoon/global/response/ResultCode.java
  src/main/java/com/ureca/juksoon/global/s3/FilePath.java
  src/main/java/com/ureca/juksoon/global/s3/S3Config.java
  src/main/java/com/ureca/juksoon/global/s3/S3Service.java
  src/main/resources/application.yml
Labels: :sparkles: feat

#4 [FIX] CORS 에러 해결
  src/main/java/com/ureca/juksoon/domain/store/controller/StoreController.java
  src/main/java/com/ureca/juksoon/global/config/SecurityConfig.java
  src/main/java/com/ureca/juksoon/global/security/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/ureca/juksoon/global/security/oauth/handler/CustomOAuth2AuthenticationSuccessHandler.java
  src/main/resources/application.yml
Labels: :fire: !HOTFIX

#5 [Fix] S3 파일명 오류 수정
  .github/pull_request_template.md
  src/main/java/com/ureca/juksoon/domain/user/dto/request/UserRoleReq.java
  src/main/java/com/ureca/juksoon/domain/user/dto/responce/UserLoginRes.java
  src/main/java/com/ureca/juksoon/domain/user/dto/responce/UserRoleRes.java
  src/main/java/com/ureca/juksoon/global/response/ResultCode.java
  src/main/java/com/ureca/juksoon/global/s3/S3Service.java
  src/main/resources/application.yml
Labels: :lady_beetle: fix

#7 [Feature] Feed 관련 API 구현
  build.gradle
  src/main/generated/com/ureca/juksoon/domain/common/QBaseEntity.java
  src/main/generated/com/ureca/juksoon/domain/feed/entity/QFeed.java
  src/main/generated/com/ureca/juksoon/domain/feed/entity/QFeedFile.java
  src/main/generated/com/ureca/juksoon/domain/reservation/entity/QReservation.java
  src/main/generated/com/ureca/juksoon/domain/store/entity/QStore.java
  src/main/generated/com/ureca/juksoon/domain/user/entity/QUser.java
  src/main/generated/com/ureca/juksoon/global/refresh/entity/QRefreshToken.java
  src/main/java/com/ureca/juksoon/domain/feed/controller/FeedController.java
  src/main/java/com/ureca/juksoon/domain/feed/dto/request/CreateFeedReq.java
  src/main/java/com/ureca/juksoon/domain/feed/dto/request/ModifyFeedReq.java
  src/main/java/com/ureca/juksoon/domain/feed/dto/response/CreateFeedRes.java
  src/main/java/com/ureca/juksoon/domain/feed/dto/response/DeleteFeedRes.java
  src/main/java/com/ureca/juksoon/domain/feed/dto/response/GetFeedDetailRes.java
  src/main/java/com/ureca/juksoon/domain/feed/dto/response/GetFeedRes.java
  src/main/java/com/ureca/juksoon/domain/feed/dto/response/GetHomeInfoRes.java
  src/main/java/com/ureca/juksoon/domain/feed/dto/response/GetMypageInfoRes.java
  src/main/java/com/ureca/juksoon/domain/feed/dto/response/ModifyFeedRes.java
  src/main/java/com/ureca/juksoon/domain/feed/entity/Category.java
  src/main/java/com/ureca/juksoon/domain/feed/entity/Feed.java
  src/main/java/com/ureca/juksoon/domain/feed/entity/FeedFile.java
  src/main/java/com/ureca/juksoon/domain/feed/entity/FileType.java
  src/main/java/com/ureca/juksoon/domain/feed/entity/SortType.java
  src/main/java/com/ureca/juksoon/domain/feed/entity/Status.java
  src/main/java/com/ureca/juksoon/domain/feed/repository/CustomFeedRepository.java
  src/main/java/com/ureca/juksoon/domain/feed/repository/CustomFeedRepositoryImpl.java
  src/main/java/com/ureca/juksoon/domain/feed/repository/FeedFileRepository.java
  src/main/java/com/ureca/juksoon/domain/feed/repository/FeedRepository.java
  src/main/java/com/ureca/juksoon/domain/feed/service/FeedService.java
  src/main/java/com/ureca/juksoon/domain/reservation/entity/Reservation.java
  src/main/java/com/ureca/juksoon/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/ureca/juksoon/domain/store/repository/StoreRepository.java
  src/main/java/com/ureca/juksoon/domain/store/service/StoreService.java
  src/main/java/com/ureca/juksoon/domain/user/controller/UserController.java
  src/main/java/com/ureca/juksoon/domain/user/dto/response/UserLoginRes.java
  src/main/java/com/ureca/juksoon/domain/user/dto/response/UserRoleRes.java
  src/main/java/com/ureca/juksoon/domain/user/service/UserService.java
  src/main/java/com/ureca/juksoon/global/config/QueryDslConfig.java
  src/main/java/com/ureca/juksoon/global/response/ResultCode.java
  src/main/java/com/ureca/juksoon/global/s3/S3Service.java
Labels: :sparkles: feat

#9 [Refactor] FeedFile 삽입 시 bulk insert 적용
  build.gradle
  src/main/java/com/ureca/juksoon/domain/feed/controller/FeedController.java
  src/main/java/com/ureca/juksoon/domain/feed/repository/FeedFileJdbcRepository.java
  src/main/java/com/ureca/juksoon/domain/feed/repository/FeedFileJdbcRepositoryImpl.java
  src/main/java/com/ureca/juksoon/domain/feed/repository/FeedFileRepository.java
  src/main/java/com/ureca/juksoon/domain/feed/service/FeedService.java
  src/main/java/com/ureca/juksoon/global/config/SwaggerConfig.java
  src/main/resources/application.yml
Labels: :hammer: refactor

#8 [Feat] Review CRUD 구현
  .gitignore
  src/main/java/com/ureca/juksoon/domain/common/FileType.java
  src/main/java/com/ureca/juksoon/domain/feed/entity/FeedFile.java
  src/main/java/com/ureca/juksoon/domain/feed/service/FeedService.java
  src/main/java/com/ureca/juksoon/domain/review/controller/ReviewController.java
  src/main/java/com/ureca/juksoon/domain/review/dto/request/ReviewReq.java
  src/main/java/com/ureca/juksoon/domain/review/dto/response/CreateReviewRes.java
  src/main/java/com/ureca/juksoon/domain/review/dto/response/DeleteReviewRes.java
  src/main/java/com/ureca/juksoon/domain/review/dto/response/GetReviewsRes.java
  src/main/java/com/ureca/juksoon/domain/review/dto/response/ModifyReviewRes.java
  src/main/java/com/ureca/juksoon/domain/review/dto/response/ReviewWithFiles.java
  src/main/java/com/ureca/juksoon/domain/review/entity/Review.java
  src/main/java/com/ureca/juksoon/domain/review/entity/ReviewFile.java
  src/main/java/com/ureca/juksoon/domain/review/repository/ReviewFileRepository.java
  src/main/java/com/ureca/juksoon/domain/review/repository/ReviewRepository.java
  src/main/java/com/ureca/juksoon/domain/review/service/ReviewService.java
  src/main/java/com/ureca/juksoon/global/response/ResultCode.java
Labels: :sparkles: feat

#10 [Fix] 수정 요청 사항 전체 반영
  Dockerfile
  src/main/java/com/ureca/juksoon/domain/feed/controller/FeedController.java
  src/main/java/com/ureca/juksoon/domain/feed/dto/response/GetFeedRes.java
  src/main/java/com/ureca/juksoon/domain/feed/dto/response/GetHomeInfoRes.java
  src/main/java/com/ureca/juksoon/domain/feed/dto/response/GetMypageInfoRes.java
  src/main/java/com/ureca/juksoon/domain/feed/entity/Feed.java
  src/main/java/com/ureca/juksoon/domain/feed/entity/SortType.java
  src/main/java/com/ureca/juksoon/domain/feed/repository/CustomFeedRepository.java
  src/main/java/com/ureca/juksoon/domain/feed/repository/CustomFeedRepositoryImpl.java
  src/main/java/com/ureca/juksoon/domain/feed/service/FeedService.java
Labels: :lady_beetle: fix, :page_facing_up: docs, :hammer: refactor

#11 [Hotfix] store 구조 수정
  src/main/java/com/ureca/juksoon/domain/store/controller/StoreController.java
  src/main/java/com/ureca/juksoon/domain/store/dto/request/StoreCreateReq.java
  src/main/java/com/ureca/juksoon/domain/store/dto/request/StoreReq.java
  src/main/java/com/ureca/juksoon/domain/store/dto/request/StoreUpdateReq.java
  src/main/java/com/ureca/juksoon/domain/store/dto/response/CreateStoreRes.java
  src/main/java/com/ureca/juksoon/domain/store/dto/response/ModifyStoreRes.java
  src/main/java/com/ureca/juksoon/domain/store/dto/response/StoreReadRes.java
  src/main/java/com/ureca/juksoon/domain/store/entity/Store.java
  src/main/java/com/ureca/juksoon/domain/store/service/StoreService.java
  src/main/java/com/ureca/juksoon/global/config/SecurityConfig.java
Labels: :fire: !HOTFIX

#13 [Fix] 가게 로고 이미지 없을때 😱
  src/main/java/com/ureca/juksoon/domain/store/service/StoreService.java
Labels: :lady_beetle: fix

#18 [Fix] 피드 수정 예외 처리
  src/main/java/com/ureca/juksoon/domain/feed/service/FeedService.java
Labels: :lady_beetle: fix

#19 fix: 피드 가격순 정렬 오류 수정
  src/main/java/com/ureca/juksoon/domain/feed/service/FeedService.java
Labels: :lady_beetle: fix

#25 [Fix] 피드 순서 정렬
  src/main/java/com/ureca/juksoon/domain/feed/repository/CustomFeedRepositoryImpl.java
  src/main/java/com/ureca/juksoon/domain/feed/service/FeedService.java
Labels: :fire: !HOTFIX
